apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-uploader.fullname" . }}
  labels:
    {{- include "video-uploader.labels" . | nindent 4 }}
data:
  {{- with .Values.uploader.config }}
  uploaderconfig.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ormconfig.yml: |
    default:
      type: postgres
      host: {{ .Release.Name }}-postgresql
      port: 5432
      {{- with .Values.global.postgresql }}
      username: {{ .postgresqlUsername }}
      password: {{ .postgresqlPassword }}
      database: {{ .postgresqlDatabase }}
      {{- end }}
      logging: false
      entities:
        - "/app/entity/**/*.js"
      migrations:
        - "/app/migration/**/*.js"
      subscribers:
        - "/app/subscriber/**/*.js"
      cli:
        entitiesDir: "/app/entity"
        migrationsDir: "/app/migration"
        subscribersDir: "/app/subscriber"
  
